services:
  backend:
    build:
      context: .
      target: dev
    image: fastapi-boilerplate-dev
    container_name: api
    environment:
      PATH: "/app/.venv/bin:$PATH"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000
    volumes:
      - ./.env:/app/.env
      - ./app:/app/app

  tests:
    image: fastapi-boilerplate-dev
    container_name: tests
    environment:
      PATH: "/app/.venv/bin:$PATH"
    command: python -m pytest --cov=app --cov-report=term-missing
    restart: "no"
    volumes:
      - ./.env:/app/.env
      - ./app:/app/app
      - ./tests:/app/tests
    profiles:
      - tests